import './globals.css';
import { Inter, Lora, Roboto } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-intel' });
const lora = Lora({ subsets: ['latin'], variable: '--font-lora' });
const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata = {
  title: 'Sample Menu Designs',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${roboto.variable} ${lora.variable}`}>
        {children}
      </body>
    </html>
  );
}
